package main

func main() {
	//imports()
	//packages()
	//exported_names()
	//functions()
	//functions_continued()
	//multiple_results()
	//named_results()
	//variables()
	//var_with_init()
	//short_var()
	//basic_types()
	//zeros()
	//type_conversion()
	//constants()
	//for_go()
	//go_next()
	//while()
	// ifs()
	//if_short()
	// loop_funcs(4)
	//switchs()
	//check_day()
	//defer_func()
	//defer_order()
	//pointers()
	//structs()
	//struct_fields()
	//str_literals()
	//arrays()
	//slices()
	//slices_pointers()
	//slice_literals()
	//nil_slices()
	//making()
	//tick_tack_toe()
	//appends()
	//ranges()
	//pics()
	//maps()
	//mutating_maps()
	//testing_count()
	//function_values()
	//fibo()
	//methods()
	methods_cont()


}